plugins {
    id 'java'
}

group = 'com.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // kafka clients
    implementation "org.apache.kafka:kafka-clients:3.9.1"

    // SLF4J for logging
    implementation "org.slf4j:slf4j-api:2.0.17"
    implementation "org.slf4j:slf4j-log4j12:2.0.17"
}

test {
    useJUnitPlatform()
}